server:
  port: 8090

spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, linyk
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
#        - id: path_route
#          uri: http://localhost:8123
#          predicates:
#            - Path=/api/**
#logging:
#  level:
#    org:
#      springframework:
#        cloud:
#          gateway: trace
#

dubbo:
  application:
    name: dubbo-springboot-demo-consumer
    qos-enable: false
    qos-port: 33333
    qos-accept-foreign-ip: false
  protocol:
    name: dubbo
    port: -1
  registry:
    #内置zookeeper配置 address: zookeeper://127.0.0.1:2181
    address: nacos://localhost:8848

